
version: 2

models:
    - name: my_fst_dbt_model
      description: "A starter dbt model"
      columns:
          - name: PRODUCT_ID
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_sec_dbt_model
      description: "A starter dbt model"
      columns:
          - name: PRODUCT_ID
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: first_etl
      description: "A starter dbt model"
      columns:
          - name: PRODUCT_ID
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: rename_account
      description: "A starter dbt model"
      columns:
          - name: PRODUCT_ID
            description: "The primary key for this table"
            tests:
                - unique
                - not_null                